name: User-Microservice
on:
  push:
    branches:
      - User-Microservice
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'

    
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'
          architecture: 'x64'
          check-latest: false

      - name: Build JAR file
        run: |
          mvn clean package -DskipTests 

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: '${{ secrets.DOCKERHUB_USERNAME }}/poc:User-Microservice-${{ github.run_id }}'
